---
id: '88380724'
title: 'បញ្ជា try/catch'
categories: 'Node.js'
thumb: ''
date: '2025-08-03T16:08:19'
bookTitle: 'ភាសា​ ES6 សម័យ​ទំនើប'
bookThumb: ''
bookChapter: 'អំពី​ភាព​មិន​ប្រក្រតី'
videos: ''
---
<p>try/catch គឺ​ជា​បញ្ជា​តម្រូវ​ឲ្យ​សាកល្បង​អនុវត្ត​ក្រុម​បញ្ជា​នៅ​ក្នុង​បញ្ជា try និង​តម្រូវ​ឲ្យ​អនុវត្ត​ក្រុម​បញ្ជា​នៅ​ក្នុង​បញ្ជា catch ក្នុង​ករណី​ការអនុវត្ត​ក្រុម​បញ្ជា​នៅ​ក្នុង​បញ្ជា try បង្ក​ឲ្យ​មាន​ភាពមិនប្រក្រតី​កើត​មាន​ឡើង​។ ពិនិត្យ​កម្មវិធី​ខាង​ក្រោម​នេះ​៖</p><pre><code class="language-javascript">try{
    var myDate = new Date()
    myDate.etMonth()
}catch(exception){
    console.log('An exception occured!!')
}</code></pre><p>&nbsp;</p><p>ក្នុងករណី​មាន​ភាពមិន​ប្រក្រតី​កើត​មាន​ឡើង​ បើ​យើង​មិន​ធ្វើ​អ្វី​សោះ​នោះ​ទេ កម្មវិធី​នឹង​ឈប់​លែង​ដំណើរការ​។ តែ​បើ​យើង​ប្រើ​បញ្ជា try/catch នៅ​ពេល​មានភាព​មិនប្រក្រតី​កើត​មាន​ឡើង ក្រុម​បញ្ជា​នៅ​ក្នុង​បញ្ជា​ catch នឹង​ត្រូវ​យក​ទៅ​អនុវត្ត ហើយ​​បន្ទាប់​ពី​នោះ កម្មវិធី​នឹង​មាន​ដំណើរ​​បន្ត​ទៅ​ទៀត ​ជា​ធម្មតា​ឡើង​វិញ​។</p><p>&nbsp;</p><p>ការប្រើប្រាស់​បញ្ជា try/catch នៅ​ក្នុង​កម្មវិធី​ហៅ​ថា <span style="color:hsl(0, 75%, 60%);"><strong>ការទទួល​យក​ភាពមិន​ប្រក្រតី </strong></span>(catching exception) ដោយហេតុថា នៅ​ពេល​មាន​ភាពមិនប្រក្រតី​កើត​មាន​ឡើង ក្រុម​បញ្ជា​នៅ​ក្នុង​បញ្ជា catch នឹង​ត្រូវ​យក​ទៅ​អនុវត្ត ហើយ​​កម្មវិធី​នឹង​ដំណើរ​ទៅ​ជា​ធម្មតា​​ជា​បន្ត​ទៅ​ទៀត​។ ផ្ទុយ​ទៅ​វិញ បើ​យើង​មិន​ប្រើប្រាស់​បញ្ជា try/catch ដើម្បី​ទទួល​យក​ភាព​មិន​ប្រក្រតី​ទេ កម្មវិធី​នឹង​ឈប់​លែង​ដំណើរការ​ នៅ​ត្រង់​កន្លែង​ដែល​មាន​ភាពមិនប្រក្រតី​នោះ​។</p><p>&nbsp;</p><p>ការទទួល​យក​ភាព​មិនប្រក្រតី​ត្រូវ​ធ្វើ​ឡើង​ដូច​ខាង​ក្រោម​នេះ​៖</p><pre><code class="language-javascript">try{
    var myDate = new Date()
    myDate.etMonth()
}catch(exception){
    console.log(`An exception of the type ${exception.name} occured!!`)
}</code></pre>